server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zayan-khan1/config-repo.git
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
